### ISSUE TITLE
Enable Right Encoder

### ISSUE THREAD

**Issue by hmfaysal** [iasoren/Lily58-Glow-Enc-Wireless-ZMK#1]
Hello, I have the Lily58 from ergohaven, which has the encoder on the right hand side. I can't figure out how to make that work. Any help would be appreciated.

**Comment by iasoren** [comment]
Are you using ZMK or VIAL/QMK? I don't have it setup with a rotary encoder on the right half so you will likely have better luck in the ergo haven Discord (if one exists)
