### ISSUE TITLE
Left side oled stopped working

### ISSUE THREAD

**Issue by hmfaysal** [iasoren/Lily58-Glow-Enc-Wireless-ZMK#3]
Hi iasoren, I had been using this repo for quite a while now, worked wonderfully. Recently after flashing, both oleds stopped working. Then suddenly the right side started working again. The right side is my master side as it has an encoder. 

I cannot figure out why the left one is not displaying anything. The traces are fine, the connections are fine. Looks like a software issue. Can you kindly help?

**Comment by iasoren** [comment]
I have not had any issues with this. Please try flashing a newer build, and hopefully that will help. I currently have the left side set as master, I wonder if that has anything to do with it.
